version: '3'
services:
  minihub-0:
    container_name: mini-hub-0
    build:
      dockerfile: ./MiniHub.Api/Dockerfile
      context: .
    environment:
      - ThisHub:Id=0
      - ThisHub:GeneratorMode=true
      - ThisHub:DelayInMilliseconds=500
      - HubRegistry:Urls=http://hub-api0/;http://hub-api1/;http://hub-api2/
      - TZ=Europe/London
#    depends_on:
#        - hub-api0
#        - hub-api1
#        - hub-api2
 