version: '3'
services:
  minihub-0:
    container_name: mini-hub-0
    build:
      dockerfile: ./MiniHub.Api/Dockerfile
      context: .
    environment:
      - ThisHub:HubId=0;
      - TZ=Europe/London
    ports: 
      - "9080:80" 